name: dockerfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
