name: dockerfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker_build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          build-args: ARCH=${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          push: false
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
